
name: Context Workflow

on: [push]

jobs:
  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Echo Repository
        run: |
        echo "Repository: ${{ github.repository }}"

      - name: Echo Branch
        run: |
        echo "Branch: ${{ github.ref_name }}"

      - name: Echo Commit SHA
        run: |
        echo "Commit SHA: ${{ github.sha }}"
