name: CI pipeline test

on: [push]

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run a one-line message
        run: echo "Hello, world!"
