name: CI Build Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print Python Version
        run: python3 --version

      - name: Print Current Directory
        run: pwd

      - name: List Repository Files
        run: ls -la
